### ISSUE TITLE
error: package directory 'python/dlcpar/deps/rasmus/ply' does not exist

### ISSUE THREAD

**Issue by davidemms** [wutron/dlcpar#1]
Hi

When I try to run the setup script to install dlcpar then I get an error:

error: package directory 'python/dlcpar/deps/rasmus/ply' does not exist

and so am unable to install this version and when I check in the repository this directory is indeed missing.

All the best
David

**Comment by wutron** [comment]
Hi David,

Apologies for the error.  I have fixed the code (and added loads of new functionality).  You can use the [official release (v1.0)](http://www.cs.hmc.edu/~yjw/software/dlcpar/).  Or feel free to use the development code on GitHub.  Please let me know if you run into other issues.

Thanks,
- Jessica

**Comment by davidemms** [comment]
Thanks, it all installs fine now!
