### ISSUE TITLE
SyntaxError when copying and adjusting bin/dlcpar -> build/scripts-3.7

### ISSUE THREAD

**Issue by mjnetherland19** [wutron/dlcpar#6]
Hello,

After cloning the git repository and running 'python setup.py install --prefix home/username/, I get the syntax errors described in the attached picture.

Can you help me understand these errors?

Thank you for your time.

![dlcpar error](https://user-images.githubusercontent.com/66214214/121816206-4b6bce00-cc48-11eb-85a3-9593c1145786.JPG)

**Comment by wutron** [comment]
Sorry, you need to use Python 2.7.x.  I know Python 2 has reached end-of-life, but I have not had a chance to update the codebase.
